name: ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-run-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t telemetry-analyzer .

      - name: Generate report in container
        run: |
          mkdir -p out
          # Update path to whichever CSV you want analyzed in CI
          docker run --rm \
            -v "$PWD:/app" \
            telemetry-analyzer \
            data/sample.csv -o out/report.md

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload artifacts to S3
        run: |
          aws s3 sync out/ "s3://${{ secrets.S3_BUCKET }}/reports/${{ github.sha }}/" --delete
          aws s3 sync out/ "s3://${{ secrets.S3_BUCKET }}/reports/latest/" --delete
